apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault
  labels:
    type: local
spec:
  storageClassName: nfs-client
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
